### ISSUE TITLE
potential dangling resources in  CommandListResourceStateTracker

### ISSUE THREAD

**Issue by BlurryLight** [NVIDIAGameWorks/nvrhi#44]
A minimal repoducable example is as following:

```cpp
  void TestRelease() {
    nvrhi::BufferDesc desc{};
    desc.keepInitialState = true;
    desc.initialState = nvrhi::ResourceStates::Common;
    desc.byteSize = 4;

    auto CmdList = GetDevice()->createCommandList();
    CmdList->open();
    {
      auto buf = GetDevice()->createBuffer(desc);
      CmdList->setBufferState(buf,nvrhi::ResourceStates::ConstantBuffer);
    }
    CmdList->close();
  }
```

It's because `CommandListResourceStateTracker`  store all resources references in raw pointers without ref counter.
When cmdlists are about to close,  they try to iterate over these resources ( `keepBufferInitialStates` / `keepTextureInitialStates`) and may trigger a crash because these resources may have been freed.

# potential fix

`CommandListResourceStateTracker`  might extend resources lifetime until closed.

**Comment by BlurryLight** [comment]
there is another dangling case:  `CommandList::Set(Permanant)Buffer/TextureState`  don't record reference in  `TrackedCommandBuffer.referencedResources;`. The resources may have been freed when `pipelinebarriers` haven't been executed on GPU.

**Comment by apanteleev** [comment]
Thank you for reporting the issue. I figured that storing strong references inside the ..StateTracker class is overkill because its methods are called from many CommandList functions, and those functions already keep strong refs to their resources. Also, `IResource*` type pointers are not passed to the state tracker at all. So, the user-facing `set(Texture|Buffer|AccelStruct)State` functions now store strong refs explicitly.
Please let me know if I missed anything.
